//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaizAuthService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogonModel", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Models")]
    public partial class LogonModel : object
    {
        
        private long appIDField;
        
        private string ipAddressField;
        
        private string passwordField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long appID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ipAddress
        {
            get
            {
                return this.ipAddressField;
            }
            set
            {
                this.ipAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginResult", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Models")]
    public partial class LoginResult : object
    {
        
        private JaizAuthService.Branch[] branchesField;
        
        private string errorField;
        
        private bool loggedInField;
        
        private string[] rolesField;
        
        private string usernameField;
        
        private string[] usersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JaizAuthService.Branch[] branches
        {
            get
            {
                return this.branchesField;
            }
            set
            {
                this.branchesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool loggedIn
        {
            get
            {
                return this.loggedInField;
            }
            set
            {
                this.loggedInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] roles
        {
            get
            {
                return this.rolesField;
            }
            set
            {
                this.rolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Models")]
    public partial class Branch : object
    {
        
        private long branch_codeField;
        
        private string branch_nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long branch_code
        {
            get
            {
                return this.branch_codeField;
            }
            set
            {
                this.branch_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branch_name
        {
            get
            {
                return this.branch_nameField;
            }
            set
            {
                this.branch_nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInRoleModel", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Models")]
    public partial class UserInRoleModel : object
    {
        
        private long appIDField;
        
        private bool inRoleField;
        
        private string rolenameField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long appID
        {
            get
            {
                return this.appIDField;
            }
            set
            {
                this.appIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool inRole
        {
            get
            {
                return this.inRoleField;
            }
            set
            {
                this.inRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rolename
        {
            get
            {
                return this.rolenameField;
            }
            set
            {
                this.rolenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetailResponse", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Models")]
    public partial class UserDetailResponse : object
    {
        
        private string emailField;
        
        private string fullnameField;
        
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullname
        {
            get
            {
                return this.fullnameField;
            }
            set
            {
                this.fullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/RoleManagerService.Memo")]
    public partial class Account : object
    {
        
        private string accountNoField;
        
        private string balanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountNo
        {
            get
            {
                return this.accountNoField;
            }
            set
            {
                this.accountNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string balance
        {
            get
            {
                return this.balanceField;
            }
            set
            {
                this.balanceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JaizAuthService.IJaizRoleManagerService")]
    public interface IJaizRoleManagerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateADUser2FA", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateADUser2FAResponse")]
        JaizAuthService.LoginResult ValidateADUser2FA(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateADUser2FA", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateADUser2FAResponse")]
        System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateADUser2FAAsync(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateADUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateADUserResponse")]
        JaizAuthService.LoginResult ValidateADUser(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateADUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateADUserResponse")]
        System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateADUserAsync(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateUserResponse")]
        JaizAuthService.LoginResult ValidateUser(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/ValidateUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/ValidateUserResponse")]
        System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateUserAsync(JaizAuthService.LogonModel clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetRoleUsers", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetRoleUsersResponse")]
        string[] GetRoleUsers(long clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetRoleUsers", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetRoleUsersResponse")]
        System.Threading.Tasks.Task<string[]> GetRoleUsersAsync(long clone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/UserInRole", ReplyAction="http://tempuri.org/IJaizRoleManagerService/UserInRoleResponse")]
        JaizAuthService.UserInRoleModel UserInRole(JaizAuthService.UserInRoleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/UserInRole", ReplyAction="http://tempuri.org/IJaizRoleManagerService/UserInRoleResponse")]
        System.Threading.Tasks.Task<JaizAuthService.UserInRoleModel> UserInRoleAsync(JaizAuthService.UserInRoleModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetRolesForUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetRolesForUserResponse")]
        string[] GetRolesForUser(string username, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetRolesForUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetRolesForUserResponse")]
        System.Threading.Tasks.Task<string[]> GetRolesForUserAsync(string username, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetUsersInRole", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetUsersInRoleResponse")]
        string[] GetUsersInRole(string role, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetUsersInRole", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetUsersInRoleResponse")]
        System.Threading.Tasks.Task<string[]> GetUsersInRoleAsync(string role, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAllRoles", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAllRolesResponse")]
        string[] GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAllRoles", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAllRolesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetUserResponse")]
        JaizAuthService.UserDetailResponse GetUser(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetUser", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetUserResponse")]
        System.Threading.Tasks.Task<JaizAuthService.UserDetailResponse> GetUserAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/LoginOnly", ReplyAction="http://tempuri.org/IJaizRoleManagerService/LoginOnlyResponse")]
        bool LoginOnly(string username, string password, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/LoginOnly", ReplyAction="http://tempuri.org/IJaizRoleManagerService/LoginOnlyResponse")]
        System.Threading.Tasks.Task<bool> LoginOnlyAsync(string username, string password, long appID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAccountDetails", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAccountDetailsResponse")]
        string GetAccountDetails(string AcctNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAccountDetails", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAccountDetailsResponse")]
        System.Threading.Tasks.Task<string> GetAccountDetailsAsync(string AcctNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAccountList", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAccountListResponse")]
        JaizAuthService.Account[] GetAccountList(string AcctNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJaizRoleManagerService/GetAccountList", ReplyAction="http://tempuri.org/IJaizRoleManagerService/GetAccountListResponse")]
        System.Threading.Tasks.Task<JaizAuthService.Account[]> GetAccountListAsync(string AcctNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IJaizRoleManagerServiceChannel : JaizAuthService.IJaizRoleManagerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class JaizRoleManagerServiceClient : System.ServiceModel.ClientBase<JaizAuthService.IJaizRoleManagerService>, JaizAuthService.IJaizRoleManagerService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public JaizRoleManagerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(JaizRoleManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), JaizRoleManagerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaizRoleManagerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(JaizRoleManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaizRoleManagerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(JaizRoleManagerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public JaizRoleManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public JaizAuthService.LoginResult ValidateADUser2FA(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateADUser2FA(clone);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateADUser2FAAsync(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateADUser2FAAsync(clone);
        }
        
        public JaizAuthService.LoginResult ValidateADUser(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateADUser(clone);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateADUserAsync(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateADUserAsync(clone);
        }
        
        public JaizAuthService.LoginResult ValidateUser(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateUser(clone);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.LoginResult> ValidateUserAsync(JaizAuthService.LogonModel clone)
        {
            return base.Channel.ValidateUserAsync(clone);
        }
        
        public string[] GetRoleUsers(long clone)
        {
            return base.Channel.GetRoleUsers(clone);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRoleUsersAsync(long clone)
        {
            return base.Channel.GetRoleUsersAsync(clone);
        }
        
        public JaizAuthService.UserInRoleModel UserInRole(JaizAuthService.UserInRoleModel model)
        {
            return base.Channel.UserInRole(model);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.UserInRoleModel> UserInRoleAsync(JaizAuthService.UserInRoleModel model)
        {
            return base.Channel.UserInRoleAsync(model);
        }
        
        public string[] GetRolesForUser(string username, long appID)
        {
            return base.Channel.GetRolesForUser(username, appID);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRolesForUserAsync(string username, long appID)
        {
            return base.Channel.GetRolesForUserAsync(username, appID);
        }
        
        public string[] GetUsersInRole(string role, long appID)
        {
            return base.Channel.GetUsersInRole(role, appID);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUsersInRoleAsync(string role, long appID)
        {
            return base.Channel.GetUsersInRoleAsync(role, appID);
        }
        
        public string[] GetAllRoles()
        {
            return base.Channel.GetAllRoles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllRolesAsync()
        {
            return base.Channel.GetAllRolesAsync();
        }
        
        public JaizAuthService.UserDetailResponse GetUser(string username)
        {
            return base.Channel.GetUser(username);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.UserDetailResponse> GetUserAsync(string username)
        {
            return base.Channel.GetUserAsync(username);
        }
        
        public bool LoginOnly(string username, string password, long appID)
        {
            return base.Channel.LoginOnly(username, password, appID);
        }
        
        public System.Threading.Tasks.Task<bool> LoginOnlyAsync(string username, string password, long appID)
        {
            return base.Channel.LoginOnlyAsync(username, password, appID);
        }
        
        public string GetAccountDetails(string AcctNo)
        {
            return base.Channel.GetAccountDetails(AcctNo);
        }
        
        public System.Threading.Tasks.Task<string> GetAccountDetailsAsync(string AcctNo)
        {
            return base.Channel.GetAccountDetailsAsync(AcctNo);
        }
        
        public JaizAuthService.Account[] GetAccountList(string AcctNo)
        {
            return base.Channel.GetAccountList(AcctNo);
        }
        
        public System.Threading.Tasks.Task<JaizAuthService.Account[]> GetAccountListAsync(string AcctNo)
        {
            return base.Channel.GetAccountListAsync(AcctNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJaizRoleManagerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IJaizRoleManagerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IJaizRoleManagerService))
            {
                return new System.ServiceModel.EndpointAddress("http://172.21.1.158:8013/RoleManagerService2FA/JaizRoleManagerService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IJaizRoleManagerService))
            {
                return new System.ServiceModel.EndpointAddress("https://jz-dc-srv-aps08.jaiz.local/RoleManagerService2FA/JaizRoleManagerService.s" +
                        "vc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IJaizRoleManagerService,
            
            BasicHttpsBinding_IJaizRoleManagerService,
        }
    }
}
